# Generated by Django 4.0.1 on 2022-02-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
