# Generated by Django 4.0.1 on 2022-02-02 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
