# Generated by Django 4.0.1 on 2022-02-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_department_created_on_department_last_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',)},
        ),
    ]
