# Generated by Django 4.0.1 on 2022-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='egn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
